export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const GET_RECIPE_DETAIL = "GET_RECIPE_DETAIL";
export const GET_DIETS = "GET_DIETS";
export const GET_RECIPES_BY_NAME = "GET_RECIPES_BY_NAME"
export const SORT_RECIPES_BY = "SORT_RECIPES_BY"
export const SET_ORIGIN_FILTER = "SET_ORIGIN_FILTER"
export const SET_DIET_FILTER = "SET_DIET_FILTER"