export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const SET_CURRENT_RECIPES = "SET_CURRENT_RECIPES";
export const GET_RECIPE_DETAIL = "GET_RECIPE_DETAIL";
export const GET_DIETS = "GET_DIETS";
export const GET_RECIPES_BY_NAME = "GET_RECIPES_BY_NAME";
export const SET_SORT_TYPE = "SET_SORT_TYPE";
export const SET_SOURCE_FILTER = "SET_SOURCE_FILTER";
export const SET_DIET_FILTER = "SET_DIET_FILTER";